/**
 * Generated by [Enunciate](http://enunciate.webcohesion.com).
 */
package com.hw.net.model

import java.io.Serializable

/**
 * @author David
 * @date 2020/7/1
 * @Copyright   Shanghai Xinke Digital Technology Co., Ltd.
 * @description
 */

open class BaseResult : Serializable {

//    /**
//     * 信息
//     */
//    var message: List<String>? = null
    /**
     * 状态码
     */
    var code = 0
    open var result: Any ?= null
}